title: CoderDojo RISE
email: dev@coderdojorise.com
description: >-
  This is the official website for CoderDojo RISE.
baseurl: ""
url: "https://coderdojorise.com"
twitter_username: CDShoredtich
github_username:  coderdojorise

# Build settings
plugins:
  - jekyll-feed
host: 0.0.0.0
port: 4400
livereload: true
destination: public

exclude: [vendor]
